### ISSUE TITLE
Portable Mode including settings

### ISSUE THREAD

**Issue by smaragdus** [StephaneCouturier/Katalog#161]
Since [Katalog](https://github.com/StephaneCouturier/Katalog) saves settings in **INI** file in User folder:

`C:\Users\User\.config\katalog_settings.ini`

I think that it would be very easy portable mode to be implemented. The program just needs to check program folder (where is the executable- **Katalog.exe**) for configuration file (**katalog_settings.ini**) when it starts and if it is there **Katalog** should use it (loading settings from it).

Additionally, besides the installer (**Katalog_installer_win64_1.00.exe**) the program may be released as an archive too, perhaps the archive containing empty configuration file (**katalog_settings.ini**) which would automatically trigger portable mode.

Off-topic- I discovered [Katalog](https://sourceforge.net/projects/katalogg/) by chance and I consider it to be a very promising program. Before I came across it I had lost hope that I would ever find a good free and open source cataloging program. So if the developer intends to improve the program further I may suggest some more enhancements for future releases. I really hope that this project is not abandoned since I have not found a better catalog program to this day.

**Comment by StephaneCouturier** [comment]
Hi smaragdus!
Thanks a lot for the feedback and the idea. 
I implemented it:  https://sourceforge.net/projects/katalogg/files/Katalog%201.01/executables/

There is a list of things to do: https://github.com/users/StephaneCouturier/projects/1
I would love to hearing more ideas or needs. 
;)

**Comment by smaragdus** [comment]
@StephaneCouturier 

Excellent work. Stephane! I downloaded and tested [Katalog](https://github.com/StephaneCouturier/Katalog) version [1.01](https://sourceforge.net/projects/katalogg/files/Katalog%201.01/executables/) and it is really portable- all data saved in program folder, including the configuration file (`katalog_settings.ini`). It was even able to use my previous settings file created by version [1.00](https://sourceforge.net/projects/katalogg/files/Katalog%201.00/executable/). Actually at first run there was a crash but after I restarted the program all was working fine.

Actually portable mode has many advantages:

- easier to backup to external drives or cloud storage;
- transfer the program from machine to machine with all data and settings;
- use multiple instances of the program with different data and settings;
- easier testing of different versions since settings are isolated;

I wonder- wouldn't it be even better if in future releases all the data (catalogs files, settings file, statistics file) to be stored inside a single sub-folder, for example `data` or `portable data` in program folder, what do you think? Anyway, now I am completely satisfied with portable mode as it is truly portable (no data is written outside program folder).

I am glad that you are still working on this program. I think there is space for improvement and fine tuning. When I have time I will do more thorough tests and I will suggest several possible enhancements (some of them will be cosmetic, mainly related to the GUI).

I am glad that I finally discovered a free and open source cataloging program. Keep the good work!

Best regards
