### ISSUE TITLE
Is a website for the project planned? 

### ISSUE THREAD

**Issue by github-userx** [StephaneCouturier/Katalog#444]
Probably too much (unnecessary) work to keep that also updated and I guess GitHub/sourceforge site can be sufficient/enough. (But I guess the current README.md could need further improvement).

I’ve already been super Impressed by how much information you provide with the wiki!

A github.io page for Katalog is already taken anyways: https://katalog.github.io/

I know the old youtube-dl project (which got superseded and forked by yt-dlp) had a simply html website: https://yt-dl.org/

**Comment by github-userx** [comment]
I think adding tags to the GitHub project could help with discovery for other people.

**Comment by github-userx** [comment]
> I think adding tags to the GitHub project could help with discovery for other people.

I propose the following tags of which you could choose the ones you seem fitting:

* catalog
* cataloging
* catalogue 
* katalog
* collections
* collection-manager
* archive 
* file sorting
* file searching
* data curation
* hdd‘s
* external drives
*

**Comment by StephaneCouturier** [comment]
Thank you for the tip and keywords !
I had actually not seen that feature in GitHub. 
I have now populated some tags or "categories".

For now I stick to a simple GitHub wiki, English only indeed, it's only just a matter of picking my battles (coding vs documenting).
There's already quite some work to update and complete it, then yes, I would look for a place for a nicer and maybe multi-lingual solution.
