### ISSUE TITLE
Display issues on Katalog for Dark Desktops

### ISSUE THREAD

**Issue by onjour** [StephaneCouturier/Katalog#523]
Hi Stephane, 

First of all, I'd like to thank you for developing this awesome tool. 

You're bringing us a true cross-platform cataloging tool which has been missing for a very long time. I hope development on the remaining OSes will go well.

I'm trying to use Katalog on my numerous computers and I struggle to get good display performance of desktops with dark themes / modes. 

Indeed on Windows 11 folders can be hard to distinguish in explore mode if a color accent is set other than 'automatic'.

On Fedora KDE Plasma Wayland, folders disappear and I have to explicitly click on a line to make them appear again. 

Sadly, changing theme on the settings doesn't help much.

Do you have any tip on how to make the rendering smoother? Thank you!

_On Fedora KDE Plasma with a dark desktop, leaving defaults_
![2024-06-03_22-53](https://github.com/StephaneCouturier/Katalog/assets/39539070/9e770d60-d374-45f5-9d61-1925a65eb419)

_On Windows 11, dark theme, leaving defaults_
![Screenshot 2024-06-04 at 10 43 36-system](https://github.com/StephaneCouturier/Katalog/assets/39539070/44eb3cc0-c99b-4258-a716-39a2f959b6a8)

_On Windows 11, dark theme, dark colors selected in settings_
![Screenshot 2024-06-04 at 10 40 24-dark](https://github.com/StephaneCouturier/Katalog/assets/39539070/45dba7c3-3ae0-446c-8679-d5ff86ea1c4e)

_On Windows 11, dark theme, light colors selected in settings_
![Screenshot 2024-06-04 at 10 41 12-light](https://github.com/StephaneCouturier/Katalog/assets/39539070/f1ced473-f71a-4660-8a45-0e8c4665000f)

**Comment by StephaneCouturier** [comment]
Hi @onjour ,
Thank you for the encouragements and the feedback!
I had never tested Windows with dark desktop theme, so thank you for these examples and screenshots.

For all dark theme desktops (any OS), I realized we were missing adapted icons for dark context.
There was only 1 set of icons for light themes (so dark icons), so I added 1 set of icons for dark themes (so light icons).
Katalog is now automatically picking them by detecting if the OS is using light or dark desktop colors.

So with next release, the use of themes could be summarized:
|Katalog theme|Context for use|
|---|---|
|Default Theme|auto adapts to any OS and light/dark themes|
|Katalog Color (light)|only for Light desktop themes (not suitable for dark desktop themes)|
|Katalog Color (dark)|only for Dark desktop themes  (not suitable for light desktop themes)|

There may be remaining issues, with none-plasma linux for instance (the dark theme is never applied in Ubuntu)
But I will release this (icons for dark desktop, and these comments in the documentation) anyhow in 2.1 (end of June).

Examples:
- Dark desktop / Default Theme
![Image](https://github.com/StephaneCouturier/Katalog/assets/8320281/c7c44a17-deef-41c1-921b-047c512cc7ca)

- Dark desktop / Katalog Color (dark)
![Image](https://github.com/StephaneCouturier/Katalog/assets/8320281/7fc56de6-4c35-409b-80ed-d10f54f81715)

- Light desktop / Katalog Color (light)
![Image](https://github.com/StephaneCouturier/Katalog/assets/8320281/66c9bf9f-6587-4a0d-b991-be6a338ffa4e)

**Comment by onjour** [comment]
Hi @StephaneCouturier ! Thank you for your exhaustive and well illustrated answer, it seems like it's exactly what's needed and it looks great to my eyes. No rush but I look forward to seeing how it turns out. I'll keep you informed! Have a nice day!

**Comment by snvoid** [comment]
Thank you @StephaneCouturier Looking forward to the next release where this is fixed. Can confirm that its happening on Windows 10 when the OS theme is dark mode. The images you shared look great

If its not too much trouble, would you be able to add some more icons to better differentiate the devices (virtual, parent, storage, etc)

**Comment by StephaneCouturier** [comment]
Thanks @onjour and @snvoid , I will re-test the Win10 Dark and post a screenshot to confirm it's ok.

For the icons, a reminder that they are currently differentiate by type (Virtual, Storage, Catalog), online/offline for Catalogs, and there is an option in Settings to make them bigger:

![devices_small-icons](https://github.com/StephaneCouturier/Katalog/assets/8320281/0fed94c4-392a-4240-9376-9666d5921cc2)

![devices_big-icons](https://github.com/StephaneCouturier/Katalog/assets/8320281/be925e51-71da-4ce0-9263-10be0742a4be)

When using smaller size, maybe Virtual and Storage look a bit too similar. I'll look if I can find a better one.
All icons are currently based on the KDE Plasma Breeze theme https://cdn.kde.org/breeze-icons/icons.html

**Comment by StephaneCouturier** [comment]
Here under Windows 10 dark desktop, it looks ok:

![win64_default t dark d](https://github.com/StephaneCouturier/Katalog/assets/8320281/d2a4dcee-2da6-445b-abd1-becc14546901)

![win64_dark t dark d](https://github.com/StephaneCouturier/Katalog/assets/8320281/4add1f44-0e88-4a9a-a77b-7a5ad02c240e)

**Comment by snvoid** [comment]
Sorry to reopen this but I've tried the latest version on Windows 10 and light mode still isn't working when Windows desktop is in dark mode. It stays in dark mode.  Please let me know if I should open a separate issue for this instead. thank you

![image](https://github.com/StephaneCouturier/Katalog/assets/60519765/43713d7d-ed2b-44c6-8e31-7559f5f7514e)

**Comment by StephaneCouturier** [comment]
Thanks a lot for the feedback,

In this released, I only fixed the icons, and tested per the doc that these cases at least are ok:
|Katalog theme|Context for use|
|---|---|
|Default Theme|auto adapts to any OS and light/dark themes|
|Katalog Color (light)|only for Light desktop themes (not suitable for dark desktop themes)|
|Katalog Color (dark)|only for Dark desktop themes  (not suitable for light desktop themes)|

It seems you would like to get a true and full light theme while using a Dark desktop, so that the whole app looks like if you were using a light desktop.
Indeed, these cases are not covered yet, I logged the idea separately: 
https://github.com/StephaneCouturier/Katalog/issues/535
