### ISSUE TITLE
SEARCH/EXPLORE: Files and folders are listed with Case insensitive sorting (now default, case sensitive as option)

### ISSUE THREAD

**Issue by onjour** [StephaneCouturier/Katalog#556]
Hi Stephane,

Thank you again for all your work, Katalog is getting better and better with each release.

I couldn't help but notice in large listings that sorting is by default sensitive to case while most my systems aren't, would you consider adding an option to have case insensitive sorting?

So instead of :

- AA _somefilename_
- AB _somefilename_
- AC _somefilename_
- Aa _somefilename_
- Ab _somefilename_
- Ac _somefilename_

We would have :
- AA _somefilename_
- Aa _somefilename_
- AB _somefilename_
- Ab _somefilename_
- AC _somefilename_
- Ac _somefilename_

Thanks and best,

**Comment by StephaneCouturier** [comment]
Thanks @onjour for the encouragement and for this!
It is something I had in mind once but never logged :)
Really appreciate the example.

I already included the change as it looks like the right default sorting.
![Image](https://github.com/user-attachments/assets/df6b20b7-f9ec-45c7-9be2-f4a673282b0c)

I will try and make it an option now.

**Comment by StephaneCouturier** [comment]
- [x] SEARCH/Search Results
- [x] EXPLORE/File & Folder list
- [x] EXPLORE/Folder Tree

**Comment by StephaneCouturier** [comment]
Also applied to Explore screen:
![explore_sorting](https://github.com/user-attachments/assets/c183114b-9b1a-4706-8897-e1baf4b89d20)
